# Keycloak SSO
# Inainte de apply, creaza ConfigMap cu realm-ul:
#   kubectl create configmap keycloak-realm \
#     --from-file=eventflow-realm.json=keycloak-config/eventflow-realm.json \
#     -n eventflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: eventflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.0
          args: ["start-dev", "--import-realm"]
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-keycloak:5432/keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventflow-secrets
                  key: KEYCLOAK_DB_PASSWORD
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: eventflow-config
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventflow-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: eventflow-config
                  key: KEYCLOAK_HOSTNAME
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: eventflow
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
